dist: trusty
sudo: required
language:
  - generic

env:
  global:
    - HOME=/home/travis
    - TARGET_PACKAGE=ros_helloworld
    - ROSINSTALL_FILE=$HOME/catkin_ws/src/$TARGET_PACKAGE/dependencies.rosinstall

before_script:
  - cd /tmp
  - git clone https://github.com/ryuichiueda/ros_setup_scripts_Ubuntu14.04_server.git
  - cd ./ros_setup_scripts_Ubuntu14.04_server
  - bash ./step0.bash
  - bash ./step1.bash
  - 
  - mkdir -p ~/catkin_ws/src
  - cd ~/catkin_ws/src
  - source /opt/ros/indigo/setup.bash
  - catkin_init_workspace
  - cd ~/catkin_ws
  - catkin_make
  - wstool init src

script:
  - cd ~/catkin_ws/src/
  - sudo apt-get install ros-indigo-desktop-full
  - if [[ -f $ROSINSTALL_FILE ]]; then wstool merge $ROSINSTALL_FILE; fi && wstool update
  - rsync -av /home/travis/build/*/$TARGET_PACKAGE ~/catkin_ws/src/$TARGET_PACKAGE/
  - source /opt/ros/indigo/setup.bash
  - source ~/catkin_ws/devel/setup.bash
  - cd ~/catkin_ws
  - catkin_make
  - source ~/catkin_ws/devel/setup.bash
  - catkin_make run_tests && catkin_make test
